buy_me_a_coffee: momentariymodder
ko_fi: momentariymodder
patreon: momentariymodder
custom: ["https://www.donationalerts.com/r/momentariymodder", "https://boosty.to/momentariymodder/donate", "https://boosty.to/momentariymodder"]
